

crsra_tabledesc <- function(x){
    tabdesc <- c("This table stores the interactions of the user with the assessment.",
                 "Link table between the assessment and the questions data and describe high-level information of questions in an assessment.",
                 "Information of checkbox quiz questions",
                 "Information of checkbox(Reflective / Ungraded) quiz questions",
                 "the patterns of the answers to a math assessment question",
                 "math assessment questions and default text displayed to learners upon answering the questions incorrectly",
                 "multiple-choice assessment questions",
                 "Information of (Reflective / Ungraded) Multiple Choice Questions",
                 "Information of choice options for a question",
                 "Information on pattern flag types",
                 "Info on pattern matching questions: Text Answer, Numeric, Regular Expression, and Math Expression",
                 "Description of the types of quiz questions",
                 "Information of quiz questions",
                 "Information of ungraded text entry question",
                 "[No table description available]",
                 "[No table description available]",
                 "[No table description available]",
                 "learner responses to assessments",
                 "[No table description available]",
                 "information of learner responses to a quiz question and the score received",
                 "The description of the varying contexts in which the user can interact with the assessment",
                 "Table that stores the single numeric pattern type questions.",
                 "Information of single numeric (Numeric match) questions",
                 "[No table description available]",
                 "Information of text exact match questions",
                 "Description of assessment types",
                 "Table of all the assessments / quizzes.",
                 "This table provides the grading event of when the user reached his or her highest grade in one course branch. Also provides the passing/not-passing state for each user and course branch.",
                 "For each course branch, provide the mapping between course branches and versioned assessments.",
                 "For each course, provide the mapping between course branches and versioned peer assignments.",
                 "For each course, provide the mapping between course branches and versioned programming assignments.",
                 "A single content item in a class such as lecture, quiz or peer review assignment.",
                 "Subsection of a single module, can be composed of multiple items in a course.",
                 "[No table description available]",
                 "This table gives the course branch details along with course version names, as set by instructors on the course web page.",
                 "Grades of a single user in each of the ungraded quizzes.",
                 "This table provides the grading event of when the user reached his or her highest grade in one course (of any branch of the course, see course_branch_grades for specific branch grades). Also provides the passing/not-passing state for each user and course.",
                 "For each course, provide the mapping between course items and versioned assessments.",
                 "Grades of user for each of the items in the course",
                 "Each item in a course can be in one of three 'states' with respect a learner passing the item.",
                 "For each course, provide the mapping between course items and versioned peer assignments.",
                 "For each course, provide the mapping between course items and versioned programming assignments.",
                 "There are many different types of of items that make up a course. Each item is given an item_type_id for ease of identification.",
                 "A single content item in a course such as lecture, quiz or peer review assignment. Note: For courses that uses the Course Versioning feature, please refer to the branch version of this table.",
                 "Subsection of a single module, can be composed of multiple items in a course. Note: For courses that uses the Course Versioning feature, please refer to the branch version of this table.",
                 "A log of when and what membership role did a user get assigned to for a course. A <user_id, course_id> tuple can have multiple values in this table to record the different roles across time. For example, a learner could have watched the preview content (BROWSER), then hit the enroll button to join (LEARNER), and then unenrolled a few days later (NOT_ENROLLED).",
                 "Contains each course's set of modules, their names, their description, and their order. Note: For courses that use the Course Versioning feature, please refer to the branch version of this table.",
                 "The descriptions of passing states for courses from the course_grades table",
                 "Contains a log of when and how a user progresses in one course item of a course, with one of two progress states: 'started' or 'completed'",
                 "A mapping table from ids to descriptions of the different course progress states, such as 1 meaning 'started'",
                 "The list of Coursera's courses on the Phoenix platform, including info on its important dates (e.g. when it was launched)",
                 "Stores answers to the questions from the demographics survey and user intent questions.",
                 "Stores choices to the questions from the demographics survey and user intent questions.",
                 "Stores question types for the demographics questions.",
                 "Stores questions from the demographics survey and user intent questions.",
                 "records when a discussion answer is marked as resolved.",
                 "records when a discussion answer was upvoted or revoked.",
                 "For each course's discussion forums, contains the list of the answers that users submitted to discussion questions.",
                 "The list of course forums. Every course branch has one root forum. Also, week and item forums are created based on the course material.",
                 "records when an discussion question is flagged as resolved",
                 "records when discussion question is followed or unfollowed",
                 "records when a discussion question was upvoted",
                 "For each course's discussion forums, contains the list of the questions, with its title, content, and author.",
                 "Executable code block engines handle evaluation requests for a single language.",
                 "Executable code block evaluations requested by learners.",
                 "Executable code block evaluators define how input from learners will be evaluated. At a high level, evaluators include a reference to a language-specific 'engine', and a 'harness' definition that parameterizes the execution mode - for example graded feedback vs. simple execution.",
                 "Contains the contents of course reviews",
                 "Contains data for course ratings",
                 "Contains the contents of comments on items or sub-items, which should generally be flags",
                 "Contains data for item-level ratings",
                 "[No table description available]",
                 "Notebook workspace provide a user with access to a Jupyter server with a persistent file system that stores personal files.",
                 "For each course's session, list the learners with the role of 'member' in that session and their start/end timestamps",
                 "Contains sessions info (e.g start and end dates) and the Course Versioning used on the Phoenix platform",
                 "The options for review schema parts that have options",
                 "The questions that the reviewer must answer",
                 "The questions that a submitter must answer in their submission",
                 "Metadata of peer assignments",
                 "Peer comments on submissions",
                 "Answers to option-based review schema questions ('options' and 'yesNo')",
                 "Answers to free response review schema questions ('singleLineInput' and 'multiLineInput')",
                 "The reviews that reviewers have made for submissions",
                 "Users may 'skip' reviewing a submission if there is a problem with it. This table records all the skips that happen.",
                 "Answers to the submission schema questions, for the 'plainText' and 'richText' submission schema part types.",
                 "Part scores that a submission gets. This only exists for submissions that have scores.",
                 "Answers to the submission schema questions, for the 'fileUpload' and 'url' submission schema part types",
                 "Submissions to peer assignments. Caveats: This table contains public submissions, draft submissions, and deleted submissions. Use the peer_submission_is_draft and peer_submission_has_been_removed_from_public columns to disambiguate",
                 "Information of asynchronously graded parts of programming assignments",
                 "possible correct responses to a part of a programming assignment. Name shortened from 'programming_assignment_submission_schema_part_possible_responses' for compatibility.",
                 "Information of individual parts of a programming assignment",
                 "Information of programming assignments",
                 "scores of individual parts of a programming assignment",
                 "The status of grading of a submission to an asynchronously graded question",
                 "Submissions to asynchronously graded questions",
                 "learner submissions to synchronously graded questions of a programming assignment",
                 "Information of learner submissions to individual parts of a programming assignment",
                 "submissions of a programming assignment",
                 "Information about Coursera users",
                 "[No table description available]")
    names(tabdesc) <- c("assessment_actions",
        "assessment_assessments_questions",
        "assessment_checkbox_questions",
        "assessment_checkbox_reflect_questions",
        "assessment_math_expression_patterns",
        "assessment_math_expression_questions",
        "assessment_mcq_questions",
        "assessment_mcq_reflect_questions",
        "assessment_options",
        "assessment_pattern_flag_types",
        "assessment_pattern_types",
        "assessment_question_types",
        "assessment_questions",
        "assessment_reflect_questions",
        "assessment_regex_pattern_flags",
        "assessment_regex_patterns",
        "assessment_regex_questions",
        "assessment_response_options",
        "assessment_response_patterns",
        "assessment_responses",
        "assessment_scope_types",
        "assessment_single_numeric_patterns",
        "assessment_single_numeric_questions",
        "assessment_text_exact_match_patterns",
        "assessment_text_exact_match_questions",
        "assessment_types",
        "assessments",
        "course_branch_grades",
        "course_branch_item_assessments",
        "course_branch_item_peer_assignments",
        "course_branch_item_programming_assignments",
        "course_branch_items",
        "course_branch_lessons",
        "course_branch_modules",
        "course_branches",
        "course_formative_quiz_grades",
        "course_grades",
        "course_item_assessments",
        "course_item_grades",
        "course_item_passing_states",
        "course_item_peer_assignments",
        "course_item_programming_assignments",
        "course_item_types",
        "course_items",
        "course_lessons",
        "course_memberships",
        "course_modules",
        "course_passing_states",
        "course_progress",
        "course_progress_state_types",
        "courses",
        "demographics_answers",
        "demographics_choices",
        "demographics_question_types",
        "demographics_questions",
        "discussion_answer_flags",
        "discussion_answer_votes",
        "discussion_answers",
        "discussion_course_forums",
        "discussion_question_flags",
        "discussion_question_followings",
        "discussion_question_votes",
        "discussion_questions",
        "ecb_engines",
        "ecb_evaluation_requests",
        "ecb_evaluators",
        "feedback_course_comments",
        "feedback_course_ratings",
        "feedback_item_comments",
        "feedback_item_ratings",
        "notebook_workspace_launchers",
        "notebook_workspaces",
        "on_demand_session_memberships",
        "on_demand_sessions",
        "peer_assignment_review_schema_part_options",
        "peer_assignment_review_schema_parts",
        "peer_assignment_submission_schema_parts",
        "peer_assignments",
        "peer_comments",
        "peer_review_part_choices",
        "peer_review_part_free_responses",
        "peer_reviews",
        "peer_skips",
        "peer_submission_part_free_responses",
        "peer_submission_part_scores",
        "peer_submission_part_urls",
        "peer_submissions",
        "programming_assignment_submission_schema_part_grid_schemas",
        "programming_assignment_submission_schema_part_possible_responses",
        "programming_assignment_submission_schema_parts",
        "programming_assignments",
        "programming_submission_part_evaluations",
        "programming_submission_part_grid_grading_statuses",
        "programming_submission_part_grid_submissions",
        "programming_submission_part_text_submissions",
        "programming_submission_parts",
        "programming_submissions",
        "users",
        "users_courses__certificate_payments")
    if (x %in% names(tabdesc)){
        print(tabdesc[[x]])
    } else {
    print("Table does not exists. Make sure the spelling is correct.")
    }
}







